# Test generated by RoostGPT for test python-test-23 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from unittest.mock import patch
from TicTacToe import choose_first

class TestChooseFirst(unittest.TestCase):

    # Test when Player 1 is chosen by the random function
    @patch('TicTacToe.random.choice', return_value='Player 1')
    def test_Choose_first_1aac01090c_player1(self, mock_random_choice):
        result = choose_first()
        self.assertEqual(result, 'Player 1', 'choose_first() did not return Player 1 when the random function did.')
    
    # Test when Player 2 is chosen by the random function
    @patch('TicTacToe.random.choice', return_value='Player 2')
    def test_Choose_first_1aac01090c_player2(self, mock_random_choice):
        result = choose_first()
        self.assertEqual(result, 'Player 2', 'choose_first() did not return Player 2 when the random function did.')

    
if __name__ == "__main__":
    unittest.main()
