# Test generated by RoostGPT for test python-test-23 using AI Type Azure Open AI and AI Model roost-gpt4-32k

# Let's import the necessary packages
import unittest
from TicTacToe import space_check 

# define a class in which the tests will run,
# it should inherit from unittest.TestCase
class TestCheckSpace(unittest.TestCase):

    # The test method should start with the word ‘test’        
    def test_Space_check_2323a5cd61(self):

        # Log to denote start of test method
        print("Running test_Space_check_2323a5cd61")

        # Given
        board = [' ' for _ in range(9)]

        # Then
        self.assertEqual(space_check(board, 2), True)

        # Setting a position and checking the space_check function
        board[2] = 'X'
        self.assertEqual(space_check(board, 2), False)

if __name__ == '__main__':

    # Start the unit test
    unittest.main()
