# Test generated by RoostGPT for test python-test-23 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from unittest.mock import patch
import builtins
from TicTacToe import play_tic_tac_toe

class TestTicTacToe(unittest.TestCase):

    @patch('builtins.input', side_effect=['y', '1', 'n'])
    def test_Play_tic_tac_toe_c1b9c031dc(self, mock_input):
        with self.assertLogs() as cm:  
            play_tic_tac_toe()
        self.assertIn('INFO:root:Player 1 has won!', cm.output)
