# Test generated by RoostGPT for test python-test-23 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from io import StringIO
from unittest.mock import patch
from TicTacToe import display_board

class TestDisplayBoard(unittest.TestCase):

    def setUp(self):
        self.board = [' ']*10

    def test_display_board(self):
        # Test empty board
        self.board = [' ']*10
        expected_output = '-------------\n|   |   |   |\n-------------\n|   |   |   |\n-------------\n|   |   |   |\n-------------\n'
        with patch('sys.stdout', new = StringIO()) as fake_out: 
            display_board(self.board)
            self.assertEqual(fake_out.getvalue(), expected_output)

    def test_display_board_filled(self):
        # Test partially filled board
        # TODO: Change the values to insert into board..
        # Set the middle row with X and first and third row with O
        self.board = [' '] * 10
        self.board[1] = 'O'
        self.board[2] = 'O'
        self.board[3] = 'O'
        self.board[4] = 'X'
        self.board[5] = 'X'
        self.board[6] = 'X'
        self.board[7] = 'O'
        self.board[8] = 'O'
        self.board[9] = 'O'
        # Check the result
        expected_output = '-------------\n| O | O | O |\n-------------\n| X | X | X |\n-------------\n| O | O | O |\n-------------\n'
        with patch('sys.stdout', new = StringIO()) as fake_out: 
            display_board(self.board)
            self.assertEqual(fake_out.getvalue(), expected_output)
            
            
if __name__ == "__main__":
    unittest.main()
