# Test generated by RoostGPT for test python-test-23 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from TicTacToe import win_check

class TestWinCheck(unittest.TestCase):
    def test_Win_check_8bf2ef15c2(self):
        board1 = ['X', 'X', 'X', 'O', 'O', '6', '7', '8', '9']
        board2 = ['O', 'X', 'X', 'O', 'O', 'X', '7', '8', '9']
        board3 = ['O', 'X', 'X', 'O', 'O', '6', '7', 'O', 'O']

        # Test both cases where a win is possible and where a win is not possible
        self.assertEqual(win_check(board1, 'X'), True, "Test failed: Expected: True, got: False")
        self.assertEqual(win_check(board2, 'X'), False, "Test failed: Expected: False, got: True")
        self.assertEqual(win_check(board3, 'O'), True, "Test failed: Expected: True, got: False")


# Run the tests
if __name__ == "__main__":
    unittest.main()
