# Test generated by RoostGPT for test python-test-23 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
from TicTacToe import full_board_check

class TestTicTacToe(unittest.TestCase):
    
    def test_Full_board_check_d5fc721cf3(self):
        # Scenario: When all positions on the board is filled
        test_board = [' ', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'O', 'X']
        result = full_board_check(test_board)
        self.assertTrue(result,'Test Failed: The board was expected to be full, but it is not.')
        
        # Scenario: Checking with a partially filled board
        test_board = [' ', 'X', 'O', 'X', 'O', ' ', 'O', 'X', ' ', 'X']
        result = full_board_check(test_board)
        self.assertFalse(result, 'Test Failed: The board was expected to be not full, but it is.')

        # Handling Edge Case: Empty Board should return False since all positions are ' '  
        test_board = [' ']*10
        result = full_board_check(test_board)
        self.assertFalse(result, 'Test Failed: The board was expected to be not full, but it is.')
        
if __name__ == '__main__':
    unittest.main()
