# Test generated by RoostGPT for test python-test-23 using AI Type Azure Open AI and AI Model roost-gpt4-32k

import unittest
import random
from TicTacToe import choose_first

class TestChooseFirst(unittest.TestCase):
    
    def setUp(self):
        self.result_set = {'Player 1', 'Player 2'}
        
    def test_Choose_first_1aac01090c(self):
        """Test that the function returns only 'Player 1' or 'Player 2'"""
        result = choose_first()
        self.assertIn(result, self.result_set)

    def test_repeatability(self):
        """Test that the function works fine under repeated usage"""
        for _ in range(10000):
            result = choose_first()
            # Checking if the result obtained is either 'Player 1' or 'Player 2'
            self.assertIn(result, self.result_set)
            

if __name__ == '__main__':
    unittest.main()
